base_url = "https://example.com"
title = "Snip"

compile_sass = false
highlight_code = true
highlight_theme = "solarized-light"
build_search_index = false
generate_rss = true

taxonomies = [
    {name = "tags", rss = true}
]

[extra]
date_format = "%d/%m/%Y"
